import fs from 'node:fs'; import path from 'node:path';
import { fileURLToPath as __f } from 'node:url';
const REPO = path.resolve(path.dirname(__f(import.meta.url)), '..', '..');
const assets = path.join(REPO, 'web', 'assets');
const wasm=await import(path.join(REPO,'crates/mathtex-wasm/pkg-node/mathtex_wasm.js'));
const packaged=new Uint8Array(fs.readFileSync(path.join(assets,'format.pkg')));
const FONTS=new Map(); for(const f of fs.readdirSync(assets)) if(f.endsWith('.otf')) FONTS.set(f.toLowerCase().replace(/\.otf$/,''), new Uint8Array(fs.readFileSync(path.join(assets,f))));
const norm=n=>{n=String(n).trim();const m=n.match(/^\[([^\]]+)\]/);if(m)n=m[1];return n.split(/[:/]/)[0].toLowerCase().replace(/\.otf$/,'');};
const resolve=n=>FONTS.get(norm(n))||null;
const t=k=>{const a=process.hrtime.bigint();const r=k();return [Number(process.hrtime.bigint()-a)/1e6, r];};
const ex=String.raw`\frac{-b\pm\sqrt{b^2-4ac}}{2a}`;
let [ctor, sess]=t(()=>new wasm.Session(packaged, resolve));
console.log('Session ctor (one-time):', ctor.toFixed(1),'ms');
for(let i=0;i<10;i++) sess.render(ex);
const med=arr=>{arr.sort((a,b)=>a-b);return arr[arr.length>>1];};
let sT=[]; for(let i=0;i<30;i++) sT.push(t(()=>sess.render(ex))[0]);
let oT=[]; for(let i=0;i<10;i++) oT.push(t(()=>wasm.render(packaged,resolve,ex))[0]);
console.log('Session.render median:', med(sT).toFixed(2),'ms   (paths='+ (sess.render(ex).match(/<path/g)||[]).length +')');
console.log('one-shot render median:', med(oT).toFixed(2),'ms');
console.log('speedup:', (med(oT)/med(sT)).toFixed(1)+'x');
